### ISSUE TITLE
Problem during compilation

### ISSUE THREAD

**Issue by Katkat95** [tge-was-taken/Atlus-Script-Tools#10]
After unpacking the file fscr0150_002_100.bf, I had no problems, just that at the time of compiling I have an error that appeared, I attach the file log.

[AtlusScriptCompiler.log](https://github.com/TGEnigma/AtlusScriptToolchain/files/2238949/AtlusScriptCompiler.log)

**Comment by tge-was-taken** [comment]
Log has been truncated, so not much I can do to solve this.
