### ISSUE TITLE
Unable to extract flowscript from certain P3P BF files

### ISSUE THREAD

**Issue by heroed** [tge-was-taken/Atlus-Script-Tools#11]
I've been working on a mod for P3P, and for some reason, this tool is only able to extract flowscripts from about half the files I want to work with. The other half are giving me the attached error message.

[AtlusScriptCompiler.log](https://github.com/TGEnigma/AtlusScriptToolchain/files/2284335/AtlusScriptCompiler.log)

**Comment by TGEnigma** [comment]
No function library for P3P has been dumped, therefore you can't decompile scripts properly.
Each game has their own unique function library, and it's necessary to have the proper one dumped in order to be able to decompile scripts successfully.

**Comment by heroed** [comment]
Ah, okay. Is it possible for me to dump the library myself?

**Comment by TGEnigma** [comment]
If you're tech savvy enough, you should be able to use: https://github.com/TGEnigma/AtlusScriptToolchain/blob/master/Scripts/ScriptInterpreterCOMMTableToJson_P3P4.py
All you'd have to do is find the right addresses for P3P and run the script in IDA.
