### ISSUE TITLE
Convert ISO to BMD/BF?

### ISSUE THREAD

**Issue by SpongebobSquamirez** [tge-was-taken/Atlus-Script-Tools#16]
Apparently the AtlusScriptToolChain has support for Digital Devil Saga, but it sounds like it only works on BMD and BF files. I only have an ISO, which extracts to irx, ddt, DAT, and img files, and something called SLPM_655.97 that extracts to a bunch of .blah files. How do I get BMD/BF files? I should note that I'm working with the Japanese version of the game.

Or if you have the Japanese script files then that I could really just use those directly.

**Comment by TGEnigma** [comment]
DDS3Pack can be used to extract the DDS3.img/ddt pair. You can find it here: https://github.com/TGEnigma/AtlusFileSystemLibrary/releases

**Comment by weirdalsuperfan** [comment]
YOU. ARE. A. HEROOOOO.

I was able to extract the files with DDS3Pack, but actually...the files seem to be encoded in a way I can't decode. I've tried Shift-JIS and UTF-8. I'm not really sure where to go from here. Do you know if the game script/dialogue files are in there, or how I can decode them?

For posterity: I ran the command `DDS3Pack.exe unpack dds3.img dds3img` to extract the img file to a directory named dds3img (replace the filename(s) with the right path as appropriate). Then I did something similar for the .ddt file, but the output was the exact same (I checked the hash), so I guess they really are a pair and the program can find them both with a single input.

**Comment by TGEnigma** [comment]
The character mappings differ from game to game, hence why it can't extract the japanese characters properly.
If you would to add one, you could do so by mapping out the characters in the font bitmap.
The FNT file contains the font bitmap of the game which can be extracted using Persona Editor (https://github.com/Meloman19/PersonaEditor)
If you provide text file containing the mapping I can arrange something.
Futhermore, the LB files can be unpacked with LBPack from PackTools.
