### ISSUE TITLE
P3P library and encoding not specified in usage information

### ISSUE THREAD

**Issue by kdports** [tge-was-taken/Atlus-Script-Tools#46]
The usage information for encoding and library specifies options for P3, P4, and P5 but not for P3P, which requires its own option selection. Adding P3P could make this easier and more intuitive for use.

Current functionality:
![image](https://user-images.githubusercontent.com/48396657/177990149-14370928-3900-4e96-ad62-13732c2a1585.png)

Expected functionality:
The encoding explanation would have a section for P3P.

**Comment by tge-was-taken** [comment]
Fixed in 0a008c55f3400860682203b8c5448c9a06ffeeae
