### ISSUE TITLE
Doesn't seem to work with .bf files from 'Trauma Team'

### ISSUE THREAD

**Issue by Shokupanda** [tge-was-taken/Atlus-Script-Tools#47]
When I try to decompile .bf files from the Atlus Game 'Trauma Team' (Wii), it gives me the following error:

![image](https://user-images.githubusercontent.com/23729870/185747513-9e168ede-bc7c-4f19-9e13-69a74e27f190.png)

**Comment by tge-was-taken** [comment]
Message files might be supported now as of 791cd1f930b67ae2cdae362cc9a4a5012e7f0952.
FlowScript library will need to be dumped however.

**Comment by Shokupanda** [comment]
Hey, awesome! I can now successfully decompile the .bf files from the 'advmap' folder. The .bm2 files from the 'comic' folder will still give me an error, though. Same for the .bf files from the 'flow' folder.
![image](https://github.com/user-attachments/assets/41e879ad-4336-4533-8e49-8805b7cfabd4)
