### ISSUE TITLE
Add P3P & P4G Traditional Chinese charsets .tsv support

### ISSUE THREAD

**Issue by EditorKos** [tge-was-taken/Atlus-Script-Tools#63]
Currently I'm trying to make a certain P3P mod into Traditional Chinese. Since there's no such charset tsv files for P3P & P4G in the tool yet, using AtlusScriptCompiler to extract stuff from .bf files will result in errors. Thankfully P3P has the same font mapping table with P4G, so I decided to create both ones to help anyone have the same problem. Maybe @tge-was-taken can update the release with these.

[P3P+P4G_CHT_tsv.zip](https://github.com/tge-was-taken/Atlus-Script-Tools/files/10939377/P3P%2BP4G_CHT_tsv.zip)

For now if anyone wants to use it, put the tsv. files in "Charsets" folder, then use the codes below in cmd to decompile & compile.

P3P:
`AtlusScriptCompiler.exe (filename).bf -Decompile -Library P3P -Encoding P3P_CHT`
`Atlusscriptcompiler.exe (filename).bf.flow -Compile -OutFormat V1 -Library P3P -Encoding P3P_CHT`

P4G:
`AtlusScriptCompiler.exe (filename).bf -Decompile -Library P4G -Encoding P4G_CHT`
`Atlusscriptcompiler.exe (filename).bf.flow -Compile -OutFormat V1 -Library P4G -Encoding P4G_CHT`

**Comment by tge-was-taken** [comment]
Thanks!
Fixed by [5df25fb](https://github.com/tge-was-taken/Atlus-Script-Tools/commit/5df25fbb8720b40488f0070c93dcce1302bb302b)
