### ISSUE TITLE
Can't download the latest build

### ISSUE THREAD

**Issue by TitleChanQWERTY** [tge-was-taken/Atlus-Script-Tools#85]
Sorry for the question. 
I can't figure out where and how to download the latest version of this utility. I need to decompile the P3RE files

![image](https://github.com/user-attachments/assets/654543ab-d7ad-4627-842c-dc4031b8b03d)
![image](https://github.com/user-attachments/assets/23934191-14d2-41fc-9fe2-8ecb6656d370)

I just don't understand why there are no Artifacts even where it shows that they are there.

**Comment by tge-was-taken** [comment]
Artifacts expire after a month, however this might be an unrelated UI glitch.
