### ISSUE TITLE
P5R crashes when certain FHIT BFs are recompiled

### ISSUE THREAD

**Issue by ShrineFox** [tge-was-taken/Atlus-Script-Tools#96]
Steps to reproduce:
- Recompile (with or without hooks) ``FIELD/HIT/FHIT_009_002_00.BF``
- Interact with the door leading inside Cafe Leblanc
  
Some observations:
![image](https://github.com/user-attachments/assets/0b74165e-d48c-4ada-bf8f-83338ec78949)
- Looking at the recompiled BF with PersonaEditor, there is a new .DAT appended to the end of the file filled with zeroes.  
- When the original BMD is re-injected using PersonaEditor, the script works as intended.
- When the game tries to get the speaker name it returns a nonsense address causing the crash, leading AnimatedSwine to believe it's related to the relocation table.
- it's possible that this file uses a pointer to data that is not used in any way by the compiler, perhaps because most other files dont use it (according to TGE)
- Other users have reported other scripts behaving similarly when compiled, such as the phone in Leblanc
  
The main reason I'd like to see this resolved is so I can use edited BMDs on these fields, since the PersonaEditor workaround only allows for .FLOW edits, and this prevents me from using Reloaded-II compiler integrations with these scripts entirely.

**Comment by tge-was-taken** [comment]
[73ee27a](https://github.com/tge-was-taken/Atlus-Script-Tools/commit/73ee27a3d1e547d50b15ccf9e9c09039f3dca983)
I fixed a couple of bugs that popped up in this file and some others. I'd like to believe this is fixed now, however I can't test this myself. Is it possible for you to test it with the latest build?

**Comment by ShrineFox** [comment]
Thank you! Seems to work great now. I'll open another issue if I run into something similar again
